![image.png](attachment:image.png)

# Práctica Extra Sprint 3: Algebra y Numpy

* Tanto si quieres ampliar tu destreza con Numpy como si necesitas recuperar el sprint, aquí tienes dos ejercicios que te permitirán conseguirlo.
* Descargalo en tu ordenador, hazlo en él y súbelo a tu repo personal si quieres o necesitas que cuente.


## PARTE I


<img src='https://i0.wp.com/contraste.info/desarrollo/wp-content/uploads/2015/04/Marsattacks_FichaCine_5566706.jpg?fit=260%2C180&ssl=1' width="300">
                                                                                                
Hemos sido invadidos por los extraterrestres. El Gobierno ha prohibido toda comunicación escrita en castellano. Para poder comunicarnos, debemos generar mensajes de hasta 9 letras, codificados conforme al siguiente diccionario:

```Python
{'A':8,
 'B':7,
 'C':5,
 'D':13,
 'E':9,
 'F':16,
 'G':18,
 'H':22,
 'I':4,
 'J':23,
 'K':11,
 'L':3,
 'M':21,
 'N':1,
 'O':6,
 'P':15,
 'Q':12,
 'R':19,
 'S':2,
 'T':14,
 'U':17,
 'V':20,
 'W':25,
 'X':24,
 'Y':10,
 'Z':26
}

```

Por ejemplo, el mensaje "MARCIANOS" lo codificaríamos como "21 8 19 5 4 8 1 6 2"

Para poder enviar mensajes, debemos introducir los dígitos en una matriz 3x3. En este ejemplo, la matriz sería:

$$A=\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}$$

A continuación, hay que multiplicar por la izquierda esta matriz por otra proporcionada por el Gobierno:

$$C=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}$$

Por tanto, el mensaje resultante sería:

$$Z = CA=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}=\begin{bmatrix}43 & 22 & 40 \\ 22 & 14 & 21 \\ 5 & 4 & 8\end{bmatrix}$$

El receptor del mensaje deberá decodificarlo multiplicando la matriz $Z$ por la matriz $C^{-1}$ (por la izquierda):

$$C^{-1}Z=A$$

**SE PIDE:**
1. Implementa una función para enviar mensajes de 9 letras codificados
> 1.1 Genera los dígitos correspondientes al mensaje a partir del diccionario y guárdalo en una lista  
> 1.2 Haz un reshape de la lista para transformarlo en un array de numpy 3x3  
> 1.3 Genera la matriz $Z=CA$, que será el output de la función
2. Implementa una función para decodificar mensajes de 9 letras
> 2.1 Crea un nuevo diccionario, donde se inviertan las claves y los valores del original  
> 2.2 Realiza la operación $C^{-1}Z=A$ y convierte la matriz a un vector con el método `flatten()`  
> 2.3 Recorre los elementos del vector para generar el mensaje decodificado usando el diccionario creado en 2.1

Consejo: Antes de implementar la función, reproduce el ejemplo del enunciado. Cuando te funcione, encapsula tu código en funciones

{'A': 8, 'B': 7, 'C': 5, 'D': 13, 'E': 9, 'F': 16, 'G': 18, 'H': 22, 'I': 4, 'J': 23, 'K': 11, 'L': 3, 'M': 21, 'N': 1, 'O': 6, 'P': 15, 'Q': 12, 'R': 19, 'S': 2, 'T': 14, 'U': 17, 'V': 20, 'W': 25, 'X': 24, 'Y': 10, 'Z': 26}


In [1]:
import numpy as np
diccionario_codigo = {'A':8,
 'B':7,
 'C':5,
 'D':13,
 'E':9,
 'F':16,
 'G':18,
 'H':22,
 'I':4,
 'J':23,
 'K':11,
 'L':3,
 'M':21,
 'N':1,
 'O':6,
 'P':15,
 'Q':12,
 'R':19,
 'S':2,
 'T':14,
 'U':17,
 'V':20,
 'W':25,
 'X':24,
 'Y':10,
 'Z':26
}
print(diccionario_codigo)

{'A': 8, 'B': 7, 'C': 5, 'D': 13, 'E': 9, 'F': 16, 'G': 18, 'H': 22, 'I': 4, 'J': 23, 'K': 11, 'L': 3, 'M': 21, 'N': 1, 'O': 6, 'P': 15, 'Q': 12, 'R': 19, 'S': 2, 'T': 14, 'U': 17, 'V': 20, 'W': 25, 'X': 24, 'Y': 10, 'Z': 26}


In [44]:
# Función codificación mensajes
# Entrada del mensaje (por especificaciones solo 9 letras la palabra)
mensaje = input("Inroduce un mensaje de nueve letras \n")

# Función que cambia las letras del mensaje a letras mayúsculas
def letras_mayusculas(mensaje):
    mensaje_mayus = mensaje.upper()
    letras_solas = list(mensaje_mayus)
    return letras_solas

# Función que transforma en matriz la conversión en número de las letras
def transformar_matriz(arr_código_numerico):
    matriz_conversión = arr_código_numerico.reshape(3,3)
    return matriz_conversión

# Función que recoge a las anteriores y hace todo el recorrido
def correspondencia_codigo(mensaje):
    letras = letras_mayusculas(mensaje)
    código_numerico=[]
    for letra in letras:
        numero = diccionario_codigo[letra]
        código_numerico.append(numero)
    arr_código_numerico = np.array(código_numerico)
    matriz = transformar_matriz(arr_código_numerico)    
    return matriz    

a = correspondencia_codigo(mensaje)
print(a)

     


[[21  8 19]
 [ 5  4  8]
 [ 1  6  2]]


In [47]:
matriz_gobierno = np.array([(2,0,1,1,0,1,0,1,0)])
c = matriz_gobierno.reshape(3,3)
c
                   

array([[2, 0, 1],
       [1, 0, 1],
       [0, 1, 0]])

In [49]:
z = c.dot(a)
z

array([[43, 22, 40],
       [22, 14, 21],
       [ 5,  4,  8]])

In [50]:
# MAtriz inversa de "c"
c_inv = np.linalg.inv(c)

# Se multiplica la matriz inversa de "C" por la matriz "z" y se consigue de nuevo la matriz "a"
c_inv.dot(z)

array([[21.,  8., 19.],
       [ 5.,  4.,  8.],
       [ 1.,  6.,  2.]])

## Parte II

En el álgebra de matrices, existen tres tipos de matrices de especial interés:

1. **Matriz diagonal**: Todos los elementos son 0 excepto los de la diagonal
<img src='./img/diagonal.png' width = 200>

2. **Triangular superior**: Todos los elementos por encima de la diagonal son 0
<img src='./img/upper.png' width = 200>

3. **Triangular inferior**: Todos los elementos por debajo de la diagonal son 0
<img src='./img/lower.png' width = 200>

En numpy, las funciones `diag()`, `triu()` y `tril()` permiten hacer transformaciones de una matriz a cualquiera de las 3 anteriores

**CASO DE USO**


<img src='./img/bets.jpg' width=400>


En LaLiga se generan matrices como la siguiente, que indican la probabilidad estimada de cada resultado en un determinado partido:  

![SegmentLocal](./img/match_matrix.gif "segment")

Por ejemplo, la probabilidad estimada de que acaben 1-2 es del 3.37%  
La probabilidad de que acaben en empate sería la suma de la diagonal: $(0.0373+0.078+0.0409+0.0095+0.0012+0.0001)=16.7\%$

**SE PIDE**:

1. Implementa una función que reciba una matriz cuadrada nxn y devuelva un diccionario con la probabilidad de empate, victoria local y victoria visitante. Asegúrate de que la suma de estas tres probabilidades es próxima a 1.

2. Implementa otra función que transforme el diccionario con las probabilidades a un diccionario de cuotas redondeado a 2 decimales (la cuota la calculamos como la inversa de la probabilidad)

Prueba con esta matriz
$$ P=\begin{bmatrix}0.0373 & 0.082 & 0.013 & 0.004\\ 0.1504 & 0.098 & 0.0337 & 0.0097 \\
0.121 & 0.194 & 0.04 & 0.0118 \\ 0.088 &  0.076 & 0.032 & 0.0091\end{bmatrix}$$

In [73]:
matriz_P = np.array([[0.0373, 0.082, 0.013, 0.004],
                     [0.1504, 0.098, 0.0337, 0.0097],
                     [0.121, 0.194, 0.04, 0.0118],
                     [0.088, 0.076, 0.032, 0.0091]])
print(matriz_P)

[[0.0373 0.082  0.013  0.004 ]
 [0.1504 0.098  0.0337 0.0097]
 [0.121  0.194  0.04   0.0118]
 [0.088  0.076  0.032  0.0091]]


In [86]:
# Como no se ven las fotos no sé si esto que he hecho es correcto o no....
# Creo el diccionario
dict_probabilidad = {"Empate": " " , "Victoria_local": " ", "Victoria_visitante": " "}

# Hallo la probabilidad de cada resultado
def resultados(matriz_p):
    prob_empate = np.sum(np.diag(matriz_P))
    prob_victoria_local = 1 - prob_empate - np.sum(np.triu(matriz_P, k=1))
    prob_victoria_visitante = 1 - prob_empate - np.sum(np.tril(matriz_P, k=-1))
    lista_resultados = [prob_empate,prob_victoria_local,prob_victoria_visitante]
    calculo_probabilidad = resultados_a_dict(lista_resultados)
    return calculo_probabilidad

# Lo introduzco dentro del resultado.
def resultados_a_dict(lista_resultados):
    repeticiones = len(lista_resultados)
    control = 1
    while control <= repeticiones:
        for prob, res in zip(dict_probabilidad.keys(),lista_resultados):
            dict_probabilidad[prob] = round(res,2)
            control +=1
        return dict_probabilidad


prob_jornada = resultados(matriz_P)
prob_jornada 

{'Empate': 0.18, 'Victoria_local': 0.66, 'Victoria_visitante': 0.15}